### ISSUE TITLE
Cannot use int values as keys.

### ISSUE THREAD

**Issue by kphanipavan** [Narasimha1997/redis-pydict#3]
Hello!!

Have been using this package for a week now. I really like the simplicity of the usage. Kudos for the work : ]

While testing it initially I found the following issue. When using int values as keys, TypeError occurs.
![Screenshot_20220717_100220](https://user-images.githubusercontent.com/60005847/179384334-d22cac7e-44a1-490b-9022-ff9c133b6306.png)

I am assuming a Type Error happens if an non-string data is passed, based on the code written.

An easy fix is to wrap the `key` variable with the `str` function.

Redis itself stored integer keys as strings so the above solution should work fine.

![Screenshot_20220717_102105](https://user-images.githubusercontent.com/60005847/179384414-503a0d54-5bdb-4f91-9f52-4a472c67d47f.png)

I will create a PR for this fix soon.

**Comment by Narasimha1997** [comment]
Thank you. The PR you made will fix this.
